<?php
/**
 * @author David Voisard
 */
?>
<!--Form Information-->
<form id="product-outofstock-alert" method="post" action="<?php echo $this->getActionForm()?>">
    <div class="email-field">
        <div class="label-box">
            <label for="email"<?php echo $this->__('Notify me when available')?></label>
        </div>
        <div class="input-box">
            <input type="text" class="input-text required-entry validate-email" maxlength="255" title="Email" value="" name="email" id="email" placeholder="Enter your email address">
            <button class="button" title="Submit" type="submit"><span><span><?php echo $this->__('Submit')?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('product-outofstock-alert', true);
    //]]>
</script>